GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/2werwer

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Alex O",
  "number": "32423234"
}

###
DELETE http://localhost:3001/api/persons/69036bbed0fdc9e52d1133fb
